### PR TITLE
Frontend fixes

### PR DESCRIPTION
**Pull request by josephgknox**
# READY FOR REVIEW

# Summary
- Featured Event Card now leveraged flex shrinking and growing as needed to ensure no overlapping of content
- Mobile search is now clickable
- Mobile menu now has active states

# Needed By (Date)
- End of sprint (3/29)

# Urgency
- N/A

# Steps to Test
1. Pull this branch
2. Verify that the above three items is working (can test against screenshots in Slack in related convo we had)

# Affected Projects or Products
- MRC
- stanford_mrc

# Associated Issues and/or People
- N/A

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by josephgknox** [comment]
@pookmish I noticed that the JS to expand the menu is not working when on a subpage. That is, you cannot access the menu if you are on a level 2 or deeper page in mobile.

**Comment by pookmish** [comment]
@josephgknox I didn't have any trouble with the menu while in mobile. I tested while on the /events, /events/event-series, & on /events/event-series/bergman-lecture pages

**Comment by pookmish** [comment]
any chance you address the `|` on event patters. the location is dropping to velow the time causing the pipe to stand alone

**Comment by josephgknox** [comment]
Yeah! Done.

**Pull request merged**
