### PR TITLE
MRCD8-311 visitors grid/list floated styles

### PR DESCRIPTION
**Pull request by josephgknox**
# READY FOR REVIEW

# Summary
- Visitors Grid is now stacked cards and appears next to events on the program/event series pages, so:
- Visitor images are now floated to the left

# Needed By (Date)
- End of sprint (3/29)

# Urgency
- N/A

# Steps to Test

1. Pull this branch
2. Test an even series pages with visitors
3. Ensure that visitor images are floated to the left

# Affected Projects or Products
- MRC
- stanford_mrc

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/MRCD8-311

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by pookmish** [comment]
screen shot 2018-03-28 at 9 53 12 am
Kind of a weird break point depending on the users name length. should this be fixed?

**Comment by josephgknox** [comment]
Yeah, it should be. We don't want that behavior. There was also issues with the image outgrowing the card if there was no title (a result of floating images alongside content that is not long enough). Changed the float behavior to leverage flexbox with shrinking and growing.

**Comment by josephgknox** [comment]
This is ready for another review.

**Comment by pookmish** [comment]
It still does the same thing. but maybe it's unavoidable. Merging. we can come back to it if its a big deal. which i dont think it is at the moment

**Pull request merged**
